// DO NOT EDIT. This file is generated by `fresh`.
// This file SHOULD be checked into source version control.
// To update this file, run `fresh routes`.

import * as $0 from "./routes/api/login_callback.ts";
import * as $1 from "./routes/dashboard.tsx";
import * as $2 from "./routes/documentation/[name].tsx";
import * as $3 from "./routes/documentation.tsx";
import * as $4 from "./routes/index.tsx";
import * as $5 from "./routes/login.tsx";
import * as $6 from "./routes/_404.tsx";
import * as $$0 from "./islands/dashboard.tsx";

const manifest = {
  routes: {
    "./routes/api/login_callback.ts": $0,
    "./routes/dashboard.tsx": $1,
    "./routes/documentation/[name].tsx": $2,
    "./routes/documentation.tsx": $3,
    "./routes/index.tsx": $4,
    "./routes/login.tsx": $5,
    "./routes/_404.tsx": $6,
  },
  islands: {
    "./islands/dashboard.tsx": $$0,
  },
  baseUrl: import.meta.url,
};

export default manifest;
