// DO NOT EDIT. This file is generated by `fresh`.
// This file SHOULD be checked into source version control.
// To update this file, run `fresh routes`.

import * as $0 from "./pages/_404.tsx";
import * as $1 from "./pages/index.tsx";
import * as $2 from "./pages/documentation/[name].tsx";
import * as $3 from "./pages/documentation.tsx";

const routes = {
  pages: {
    "./pages/_404.tsx": $0,
    "./pages/index.tsx": $1,
    "./pages/documentation/[name].tsx": $2,
    "./pages/documentation.tsx": $3,
  },
  baseUrl: import.meta.url,
};

export default routes;
